services:
  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - ./backend/db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: german_bridge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
